# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy-lower:
    name: Deploy to lower
    needs:  build
    environment: lower
    runs-on: ubuntu-latest
    concurrency:
      group: lower-deploy-group
    steps:
      - name: Run a multi-line script
        run: |
          echo Deploy to lower
          sleep 5s

  deploy-upper:
    name: Deploy to upper
    needs:  deploy-lower
    environment: upper
    runs-on: ubuntu-latest
    concurrency:
      group: upper-deploy-group
      cancel-in-progress: true
    steps:
      - name: Fake deploy
        id: deploy
        run: echo DEPLOYED
      - name: Run a multi-line script
        run: |
          echo Deploy to upper
          sleep 10s
      - name: Run a multi-line script
        run: |
          echo Deploy to upper
          sleep 10s
      - name: Run a multi-line script
        run: |
          echo Deploy to upper
          sleep 10s
      - name: Record deployed
        if: ${{ always() && steps.deploy.outcome == 'success' }}
        run: |
          echo DEPLYED RECORD
    
